import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            gap: "16px",
            marginBottom: "16px",
          }}
        >
          <Link href="/client">Client</Link>
          <Link href="/server">Server</Link>
          <Link href="/auth">Auth</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
